# Курс Специализация Data Science Дипломный проект. Бриф учебного кейса 
## «Модель прогнозирования стоимости жилья для агентства недвижимости»

#### 3 Этап создания модели

В данном ноутбуке мы сделаем следующее:
* Обработаем и отнормируем признаки
* Построим "наивную" модель, предсказывающую цену по общей площади и городу (с ней будем сравнивать другие модели)
* Построим модель при помощи LinearRegression
* Обучим модель на основе случайного леса RandomForestRegressor
* Обучим модель с L1 и L2 регуляризаций ElasticNetCV
* Сделаем  модель стохастического градиентного спуска SGDRegressor
* На основе предыдущих шагов выберем оптимальную модель

In [13]:
import random
import numpy as np 
import pandas as pd 
import sys
import optuna

from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import ElasticNetCV
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
from sklearn.compose import TransformedTargetRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import SGDRegressor
from catboost import CatBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.model_selection import KFold
from sklearn import metrics
from tqdm.notebook import tqdm
from category_encoders import TargetEncoder, CatBoostEncoder
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.preprocessing import StandardScaler, PolynomialFeatures


# plt
import matplotlib.pyplot as plt
#увеличим дефолтный размер графиков
from pylab import rcParams
rcParams['figure.figsize'] = 10, 5
#графики в svg выглядят более четкими
%config InlineBackend.figure_format = 'svg' 
%matplotlib inline
#отключим оповещения
import warnings
warnings.filterwarnings("ignore")

In [14]:
# зафиксируем RANDOM_SEED, чтобы эксперименты были воспроизводимы
RANDOM_SEED = 42
TEST_SIZE = 0.2

In [15]:
df = pd.read_csv('data/data_model.csv')
display(df.head())
df.info()

,status,baths,city,sqft,zipcode,state,target,pool_encoded,Type,Year built,Heating_encoded,Cooling_encoded,Parking_encoded,fireplace_encoded,school_rating _mean,school_dist_min
0,Active,4.0,Southern Pines,2900,28387,NC,418000,False,single_family_home,2019,True,False,False,True,5.2,2.70
1,For Sale,3.0,Spokane Valley,1947,99216,WA,310000,False,single_family_home,2019,False,False,False,False,4.0,1.01
2,Active,2.0,Mason,3588,50401,IA,244900,False,single_family_home,1970,True,True,False,False,3.8,5.60
3,Other,3.0,Houston,1930,77080,TX,311995,False,single_family_home,2019,True,True,True,False,3.0,0.60
4,For Sale,2.0,Flushing,1300,11354,NY,669000,False,condo,1965,False,False,True,False,2.8,0.30

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210669 entries, 0 to 210668
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   status               210669 non-null  object
 1   baths                210669 non-null  float64
 2   city                 210669 non-null  object
 3   sqft                 210669 non-null  int64
 4   zipcode              210669 non-null  int64
 5   state                210669 non-null  object
 6   target               210669 non-null  int64
 7   pool_encoded         210669 non-null  bool
 8   Type                 210669 non-null  object
 9   Year built           210669 non-null  object
 10  Heating_encoded      210669 non-null  bool
 11  Cooling_encoded      210669 non-null  bool
 12  Parking_encoded      210669 non-null  bool
 13  fireplace_encoded    210669 non-null  bool
 14  school_rating _mean  210669 non-null  float64
 15  school_dist_min      210669 non-null  float64
dtypes: bool(5), float64(3), int64(3), object(5)
memory usage: 18.7+ MB

In [16]:
#исправим автоопределение категориальной переменной как числа
df['zipcode'] = df['zipcode'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210669 entries, 0 to 210668
Data columns (total 16 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   status               210669 non-null  object
 1   baths                210669 non-null  float64
 2   city                 210669 non-null  object
 3   sqft                 210669 non-null  int64
 4   zipcode              210669 non-null  object
 5   state                210669 non-null  object
 6   target               210669 non-null  int64
 7   pool_encoded         210669 non-null  bool
 8   Type                 210669 non-null  object
 9   Year built           210669 non-null  object
 10  Heating_encoded      210669 non-null  bool
 11  Cooling_encoded      210669 non-null  bool
 12  Parking_encoded      210669 non-null  bool
 13  fireplace_encoded    210669 non-null  bool
 14  school_rating _mean  210669 non-null  float64
 15  school_dist_min      210669 non-null  float64
dtypes: bool(5), float64(3), int64(2), object(6)
memory usage: 18.7+ MB

In [17]:
# Составим список булевых признаков:
bin_features = ['pool_encoded','Heating_encoded','Cooling_encoded','Parking_encoded','fireplace_encoded']

# Составим список категориальных признаков:
cat_features = ['status','city','zipcode','state','Type','Year built']
 
# Составим список числовых признаков:
num_features = ['baths', 'sqft', 'target', 'school_rating _mean', 'school_dist_min']

In [18]:
# подсчет количества уникальных значений в каждой категориальной колонке
for col in cat_features:
   unique_values = df[col].nunique()
   print(f"Количество уникальных значений в категориальной колонке {col}: {unique_values}")

Количество уникальных значений в категориальной колонке status: 12
Количество уникальных значений в категориальной колонке city: 1522
Количество уникальных значений в категориальной колонке zipcode: 3962
Количество уникальных значений в категориальной колонке state: 34
Количество уникальных значений в категориальной колонке Type: 12
Количество уникальных значений в категориальной колонке Year built: 205

In [19]:
def preproc_data(df_input):
    '''includes several functions to pre-process the predictor data.'''
    
    df_output = df_input.copy()
 
    # Нормализация данных и логорифмирование
    #scaler = MinMaxScaler()
    for column in num_features:
        #df_output[column] = scaler.fit_transform(df_output[[column]])[:,0]
        # Логорифмирование
        df_output[column] = df_output[column].apply(lambda x: abs(x))
        constant = 1e-6
        df_output[column] = np.log(df_output[column] + constant)
        
    # ################### Categorical Features ############################################################## 
 
    ohe_status = OneHotEncoder(sparse=False)
    ohe_state = OneHotEncoder(sparse=False)
    ohe_Type = OneHotEncoder(sparse=False)

    status_ohe = ohe_status.fit_transform(df_output['status'].values.reshape(-1,1))
    state_ohe = ohe_state.fit_transform(df_output['state'].values.reshape(-1,1))
    Type_ohe = ohe_Type.fit_transform(df_output['Type'].values.reshape(-1,1))

    le = LabelEncoder()
    state_label = le.fit_transform(df_output['state'])

    year_le = LabelEncoder()
    year_ord = year_le.fit_transform(df_output['Year built'])

    te = TargetEncoder()
    cbe = CatBoostEncoder()

    city_te = te.fit_transform(df_output['city'], df_output['target'])
    city_cbe = cbe.fit_transform(df_output['city'], df_output['target'])

    zip_te = te.fit_transform(df_output['zipcode'], df_output['target'])
    zip_cbe = cbe.fit_transform(df_output['zipcode'], df_output['target'])

    # Adding encoded categorical features to the output dataframe
    df_output = df_output.join(pd.DataFrame(status_ohe, columns=['status_' + str(cat) for cat in ohe_status.categories_[0]]))
    df_output = df_output.join(pd.DataFrame(state_ohe, columns=['state_' + str(cat) for cat in ohe_state.categories_[0]]))
    df_output = df_output.join(pd.DataFrame(Type_ohe, columns=['Type_' + str(cat) for cat in ohe_Type.categories_[0]]))
    df_output['state_label'] = state_label
    df_output['year_ord'] = year_ord
    df_output['city_te'] = city_te
    df_output['city_cbe'] = city_cbe
    df_output['zip_te'] = zip_te
    df_output['zip_cbe'] = zip_cbe

    # Dropping original categorical columns
    df_output.drop(['status', 'state', 'Type', 'city', 'zipcode','Year built'], axis=1, inplace=True)
    
    return df_output

In [20]:
# Запускаем и проверяем, что получилось
df_encoded = preproc_data(df)
df_encoded.sample(10)

,baths,sqft,target,pool_encoded,Heating_encoded,Cooling_encoded,Parking_encoded,fireplace_encoded,school_rating _mean,school_dist_min,...,Type_other,Type_ranch,Type_single_family_home,Type_townhouse,state_label,year_ord,city_te,city_cbe,zip_te,zip_cbe
162668,1.386295,7.725771,13.458836,False,True,True,True,False,0.993252,-0.843968,...,0.0,0.0,1.0,0.0,8,196,12.493241,12.484390,12.978394,12.964686
101326,0.693148,6.551080,11.695247,False,True,True,False,False,1.526057,-1.139431,...,0.0,0.0,0.0,0.0,5,158,12.515554,12.531901,12.309733,12.503405
202555,0.693148,7.575585,12.627739,False,True,True,False,False,1.386295,0.336473,...,0.0,0.0,1.0,0.0,5,199,12.529606,12.528266,12.533533,12.534881
40098,1.098613,7.938089,13.017003,True,True,True,True,True,1.386295,-0.105359,...,0.0,0.0,1.0,0.0,5,149,12.491641,12.483957,12.625563,12.427580
163452,0.693148,7.279319,12.254387,False,True,False,True,True,1.945910,0.688135,...,0.0,0.0,1.0,0.0,21,201,11.258773,11.248635,12.409136,12.111061
123560,1.098613,7.412160,13.303017,False,True,False,True,False,0.832910,-0.328503,...,0.0,0.0,0.0,0.0,1,106,13.241551,13.237890,13.085861,13.258339
156660,1.098613,7.642044,13.457406,False,True,True,True,False,1.386295,-0.274436,...,0.0,0.0,0.0,0.0,28,167,12.688819,12.682154,12.830345,12.841800
48512,1.098613,7.759614,12.554932,False,False,False,False,False,1.435085,-0.693145,...,1.0,0.0,0.0,0.0,28,204,12.444700,12.440515,12.861738,12.830884
76006,0.693148,7.272398,13.262125,False,True,False,True,False,1.704748,-0.072570,...,0.0,0.0,1.0,0.0,32,110,13.076482,13.091877,13.153610,13.146373
112629,1.098613,7.522941,12.550853,False,True,True,True,False,1.098613,-0.693145,...,0.0,0.0,1.0,0.0,5,186,12.481865,12.485916,12.582397,12.518571

In [21]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210669 entries, 0 to 210668
Data columns (total 74 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   baths                    210669 non-null  float64
 1   sqft                     210669 non-null  float64
 2   target                   210669 non-null  float64
 3   pool_encoded             210669 non-null  bool
 4   Heating_encoded          210669 non-null  bool
 5   Cooling_encoded          210669 non-null  bool
 6   Parking_encoded          210669 non-null  bool
 7   fireplace_encoded        210669 non-null  bool
 8   school_rating _mean      210669 non-null  float64
 9   school_dist_min          210669 non-null  float64
 10  status_Active            210669 non-null  float64
 11  status_Auction           210669 non-null  float64
 12  status_Back on Market    210669 non-null  float64
 13  status_Coming Soon       210669 non-null  float64
 14  status_Contingent        210669 non-null  float64
 15  status_For Rent          210669 non-null  float64
 16  status_For Sale          210669 non-null  float64
 17  status_Foreclosure       210669 non-null  float64
 18  status_Other             210669 non-null  float64
 19  status_Pending           210669 non-null  float64
 20  status_Price Change      210669 non-null  float64
 21  status_Under Contract    210669 non-null  float64
 22  state_AZ                 210669 non-null  float64
 23  state_CA                 210669 non-null  float64
 24  state_CO                 210669 non-null  float64
 25  state_DC                 210669 non-null  float64
 26  state_DE                 210669 non-null  float64
 27  state_FL                 210669 non-null  float64
 28  state_GA                 210669 non-null  float64
 29  state_IA                 210669 non-null  float64
 30  state_IL                 210669 non-null  float64
 31  state_IN                 210669 non-null  float64
 32  state_KY                 210669 non-null  float64
 33  state_MA                 210669 non-null  float64
 34  state_MD                 210669 non-null  float64
 35  state_ME                 210669 non-null  float64
 36  state_MI                 210669 non-null  float64
 37  state_MO                 210669 non-null  float64
 38  state_MS                 210669 non-null  float64
 39  state_MT                 210669 non-null  float64
 40  state_NC                 210669 non-null  float64
 41  state_NJ                 210669 non-null  float64
 42  state_NV                 210669 non-null  float64
 43  state_NY                 210669 non-null  float64
 44  state_OH                 210669 non-null  float64
 45  state_OK                 210669 non-null  float64
 46  state_OR                 210669 non-null  float64
 47  state_PA                 210669 non-null  float64
 48  state_SC                 210669 non-null  float64
 49  state_TN                 210669 non-null  float64
 50  state_TX                 210669 non-null  float64
 51  state_UT                 210669 non-null  float64
 52  state_VA                 210669 non-null  float64
 53  state_VT                 210669 non-null  float64
 54  state_WA                 210669 non-null  float64
 55  state_WI                 210669 non-null  float64
 56  Type_apartment           210669 non-null  float64
 57  Type_condo               210669 non-null  float64
 58  Type_historical          210669 non-null  float64
 59  Type_land                210669 non-null  float64
 60  Type_miscellaneous       210669 non-null  float64
 61  Type_mobile_home         210669 non-null  float64
 62  Type_modern              210669 non-null  float64
 63  Type_multi_family_home   210669 non-null  float64
 64  Type_other               210669 non-null  float64
 65  Type_ranch               210669 non-null  float64
 66  Type_single_family_home  210669 non-null  float64
 67  Type_townhouse           210669 non-null  float64
 68  state_label              210669 non-null  int64
 69  year_ord                 210669 non-null  int64
 70  city_te                  210669 non-null  float64
 71  city_cbe                 210669 non-null  float64
 72  zip_te                   210669 non-null  float64
 73  zip_cbe                  210669 non-null  float64
dtypes: bool(5), float64(67), int64(2)
memory usage: 111.9 MB

Разделим датасет

In [22]:
y = df_encoded.target.values
X = df_encoded.drop(['target'], axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=TEST_SIZE, shuffle=True, random_state=RANDOM_SEED)

# Обучение модели

## Model 1: Создадим "наивную" модель 
Эта модель будет предсказывать среднюю стоимость по общей площади и городу. 
C ней будем сравнивать другие модели.

In [23]:
# Наивная модель
class NaiveModel:
    def __init__(self):
        self.means = None

    def fit(self, X, y):
        X_df = pd.DataFrame(X, columns=['city_te', 'city_cbe'])
        y_df = pd.DataFrame(y, columns=['target'])
        df = pd.concat([X_df, y_df], axis=1)
        self.means = df.groupby(['city_te', 'city_cbe'])['target'].mean().reset_index()

    def predict(self, X):
        X = pd.DataFrame(X, columns=['city_te', 'city_cbe']).copy()
        X['mean'] = np.nan
        for idx, row in self.means.iterrows():
            X.loc[(X['city_te'] == row['city_te']) & (X['city_cbe'] == row['city_cbe']), 'mean'] = row['target']
        
        X['mean'].fillna(X['mean'].mean(), inplace=True)
        return X['mean'].to_numpy()

naive_model = NaiveModel()
naive_model.fit(X_train, y_train)
y_pred_train = naive_model.predict(X_train)
y_pred_test = naive_model.predict(X_test)

mse_train = mean_squared_error(y_train, y_pred_train)
mse_test = mean_squared_error(y_test, y_pred_test)
mae_train = mean_absolute_error(y_train, y_pred_train)
mae_test = mean_absolute_error(y_test, y_pred_test)
r2_train = r2_score(y_train, y_pred_train)
r2_test = r2_score(y_test, y_pred_test)

print(f"Train MSE: {mse_train:.2f}")
print(f"Test MSE: {mse_test:.2f}")
print(f"Train MAE: {mae_train:.2f}")
print(f"Test MAE: {mae_test:.2f}")
print(f"Train R2: {r2_train:.2f}")
print(f"Test R2: {r2_test:.2f}")

Train MSE: 0.76
Test MSE: 0.43
Train MAE: 0.64
Test MAE: 0.47
Train R2: -0.79
Test R2: -0.01

Среднеквадратичная ошибка (MSE) - это мера разности между правильными ответами и предсказаниями модели. Чем ниже значение MSE, тем лучше модель предсказывает данные. модель имеет значение 0,76 на обучающей выборке и 0,43 на тестовой выборке.

Средняя абсолютная ошибка (MAE) также меряет разницу между правильными ответами и предсказаниями, но без возведения в квадрат. Значения 0,64 и 0,47 для обучающей и тестовой выборок соответственно свидетельствуют о средней абсолютной ошибке предсказания модели.

Коэффициент детерминации (R2) - это мера, которая показывает, насколько хорошо предсказания модели объясняют изменчивость примеров. Значения R2 варьируются от -∞ до 1, где 1 означает идеальное совпадение. Отрицательные значения R2 указывают на то, что модель очень плохо предсказывает данные. В вашем случае модель имеет R2 -0,79 на обучающей выборке и -0,01 на тестовой выборке.

Интерпретация результатов: модель показывает недостаточные предсказательные способности на обучающей выборке, особенно в виду отрицательного коэффициента детерминации (R2). Однако на тестовой выборке показатели немного лучше, со значениями MSE и MAE меньше, чем на обучающей выборке, и R2, приближающимся к нулю. Это может указывать на проблему с переобучением модели

## Model 2: LinearRegression

In [24]:
# создаём модель линейной регрессии
model = LinearRegression(fit_intercept=False)

# вычисляем коэффициенты регрессии
model.fit(X_train, y_train)

# делаем предсказания с помощью модели
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# вычисляем требуемые метрики
mse_train = metrics.mean_squared_error(y_train, y_train_pred)
mse_test = metrics.mean_squared_error(y_test, y_test_pred)
mae_train = metrics.mean_absolute_error(y_train, y_train_pred)
mae_test = metrics.mean_absolute_error(y_test, y_test_pred)
r2_train = metrics.r2_score(y_train, y_train_pred)
r2_test = metrics.r2_score(y_test, y_test_pred)

# выводим метрики
print(f"Train MSE: {mse_train:.2f}")
print(f"Test MSE: {mse_test:.2f}")
print(f"Train MAE: {mae_train:.2f}")
print(f"Test MAE: {mae_test:.2f}")
print(f"Train R2: {r2_train:.2f}")
print(f"Test R2: {r2_test:.2f}")

Train MSE: 0.13
Test MSE: 0.14
Train MAE: 0.25
Test MAE: 0.26
Train R2: 0.68
Test R2: 0.68

MSE (Mean Squared Error) - средняя квадратичная ошибка. Меньшие значения MSE указывают на лучшую точность модели. Значение Train MSE = 0.02 свидетельствует о средней ошибке модели на обучающей выборке, а Test MSE = 0.02 - на тестовой выборке. Значения ошибок очень близки, что указывает на адекватное обобщение модели.

MAE (Mean Absolute Error) - средняя абсолютная ошибка. Этот показатель также отражает точность модели и чувствителен к выбросам. Train MAE = 0.10 сообщает о средней ошибке модели на обучающей выборке, а Test MAE = 0.10 - на тестовой выборке. Ошибки также близки для обоих выборок, что хорошо для модели.

R2 (коэффициент детерминации) - показатель, который отражает долю дисперсии зависимой переменной объясненной моделью. Значения R2 колеблются от 0 до 1. Чем ближе значение к 1, тем лучше модель предсказывает зависимую переменную. Train R2 = 0.61 и Test R2 = 0.61 указывают на то, что модель объясняет около 61% дисперсии зависимой переменной на обучающей и тестовой выборке.

В целом, результаты свидетельствуют о том, что модель демонстрирует среднею точность прогнозирования и адекватное обобщение на тестовых данных. Нет признаков переобучения или недообучения. Тем не менее, зависимость от объясняющих переменных составляет 61%, что оставляет место для улучшения предсказательной мощи модели. Это можно сделать, добавив новые переменные или методы оптимизации модели

## Model 3: RandomForestRegressor

In [26]:
# Создаем экземпляр модели RandomForestRegressor
rf_regressor = RandomForestRegressor(random_state=RANDOM_SEED)

# Обучаем модель на обучающих данных
rf_regressor.fit(X_train, y_train)

# Предсказания на обучающих и тестовых данных
y_train_pred = rf_regressor.predict(X_train)
y_test_pred = rf_regressor.predict(X_test)

# Вычисляем метрики
mse_train = mean_squared_error(y_train, y_train_pred)
mse_test = mean_squared_error(y_test, y_test_pred)
mae_train = mean_absolute_error(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)
r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

# Выводим метрики
print(f"Train MSE: {mse_train:.2f}")
print(f"Test MSE: {mse_test:.2f}")
print(f"Train MAE: {mae_train:.2f}")
print(f"Test MAE: {mae_test:.2f}")
print(f"Train R2: {r2_train:.2f}")
print(f"Test R2: {r2_test:.2f}")

Train MSE: 0.01
Test MSE: 0.07
Train MAE: 0.06
Test MAE: 0.16
Train R2: 0.98
Test R2: 0.84

В целом, модель показывает хорошие результаты на обучающей выборке, с низкими значениями MSE и MAE, и высоким R2. Однако, на тестовой выборке метрики немного хуже, что может указывать на переобучение - модель хорошо применяет свои наработки к обучающим данным, но менее успешна для новых данных.

Тем не менее, коэффициент детерминации на тестовой выборке равен 0.83, что говорит о том, что модель все равно оценивает данные относительно хорошо. В зависимости от конкретной задачи и требований к точности, эти результаты могут быть приемлемыми

## Model 4: ElasticNetCV

In [27]:
# Создаем и тренируем модель ElasticNetCV с кросс-валидацией по 5 фолдам
model_el = ElasticNetCV(cv=5, random_state=RANDOM_SEED)
model_el.fit(X_train, y_train)

# Предсказания для обучающей и тестовой выборок
y_train_pred = model_el.predict(X_train)
y_test_pred = model_el.predict(X_test)

# MSE
mse_train = mean_squared_error(y_train, y_train_pred)
mse_test = mean_squared_error(y_test, y_test_pred)

# MAE
mae_train = mean_absolute_error(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

# R2
r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

# Выводим метрики
print(f"Train MSE: {mse_train:.2f}")
print(f"Test MSE: {mse_test:.2f}")
print(f"Train MAE: {mae_train:.2f}")
print(f"Test MAE: {mae_test:.2f}")
print(f"Train R2: {r2_train:.2f}")
print(f"Test R2: {r2_test:.2f}")

Train MSE: 0.15
Test MSE: 0.15
Train MAE: 0.26
Test MAE: 0.26
Train R2: 0.65
Test R2: 0.65

Так как значения ошибки и коэффициента детерминации одинаковы для обучающей и тестовой выборок, мы можем сказать, что модель не переобучена или недообучена. Однако, коэффициент детерминации равный 0.54 указывает на то, что модель объясняет только около 54% изменчивости зависимой переменной

## Model 5: SGDRegressor

In [28]:
# Создание и обучение модели градиентного спуска без подбора гиперпараметров
#model_sgd = SGDRegressor(random_state=RANDOM_SEED)
#model_sgd.fit(X_train, y_train)

# Предсказание значений на тренировочном и тестовом наборах
#y_train_pred = model_sgd.predict(X_train)
#y_test_pred = model_sgd.predict(X_test)

# Расчет метрик
#mse_train = mean_squared_error(y_train, y_train_pred)
#mse_test = mean_squared_error(y_test, y_test_pred)
#mae_train = mean_absolute_error(y_train, y_train_pred)
#mae_test = mean_absolute_error(y_test, y_test_pred)
#r2_train = r2_score(y_train, y_train_pred)
#r2_test = r2_score(y_test, y_test_pred)

# Вывод результатов
#print(f"Train MSE: {mse_train:.2f}")
#print(f"Test MSE: {mse_test:.2f}")
#print(f"Train MAE: {mae_train:.2f}")
#print(f"Test MAE: {mae_test:.2f}")
#print(f"Train R2: {r2_train:.2f}")
#print(f"Test R2: {r2_test:.2f}")

* Train MSE: 1950146658224079382773760.00
* Test MSE: 1945784524795032165679104.00
* Train MAE: 1367703995238.82
* Test MAE: 1365927716077.47
* Train R2: -38710304943173374614437888.00
* Test R2: -38654499143432082475188224.00

Результаты говорят о том, что использованная модель показывает очень слабую производительность и недостаточную предсказательную способность.

Мы даже не будем добовлять ее в сравнение

In [29]:
data = {'Metric': ['Train MSE', 'Test MSE', 'Train MAE', 'Test MAE', 'Train R2', 'Test R2'],
        'NaiveModel': [0.09, 0.05, 0.24, 0.19, -0.79, -0.03],
        'LinearRegression': [0.02, 0.02, 0.10, 0.10, 0.61, 0.61],
        'RandomForestRegressor': [0.00, 0.01, 0.02, 0.06, 0.98, 0.83],
        'ElasticNetCV': [0.02, 0.02, 0.12, 0.12, 0.54, 0.54]}

df_metric = pd.DataFrame(data)
df_metric.head()

,Metric,NaiveModel,LinearRegression,RandomForestRegressor,ElasticNetCV
0,Train MSE,0.09,0.02,0.00,0.02
1,Test MSE,0.05,0.02,0.01,0.02
2,Train MAE,0.24,0.10,0.02,0.12
3,Test MAE,0.19,0.10,0.06,0.12
4,Train R2,-0.79,0.61,0.98,0.54

Исходя из предоставленных данных, можно сделать следующий общий вывод относительно различных моделей, применяемых для решения задачи регрессии:

* NaiveModel показывает самые низкие значения Test R2 и малую точность. Эта модель не подходит для прогнозирования данных в рассматриваемой задаче.

* LinearRegression и ElasticNetCV показывают схожие результаты и умеренную точность с Test MSE равным 0.02 и Test R2 равным 0.61 и 0.54 соответственно. Однако, между ними предпочтительнее использовать модель LinearRegression, так как она имеет более низкие значения ошибок (Train MAE и Test MAE).

* RandomForestRegressor демонстрирует лучшие показатели среди всех моделей с минимальным значением ошибок (Test MSE 0.01) и наиболее высоким коэффициентом детерминации (Test R2 0.83).
В результате, RandomForestRegressor является наиболее подходящей моделью для прогнозирования данных в данной регрессионной задаче, обеспечивая относительно высокую точность и наименьшие ошибки.

Хотелось бы попробовать обучить модель на полиномиальных признаках но из за большого объема данных крашится ядро, так же не хватает вычислительной мощьности для подбора гиперпараметров для модели гардиентного спуска пришлось работать без них

In [30]:
df_encoded.to_csv('data/data_model_ecod.csv', index=False)